name: test1
description: A simple command-line application.
version: 1.0.0
# homepage: https://rizad.ml

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
